### PR TITLE
A1 Mediator integration into docker-compose.yml

### PR DESCRIPTION
**Pull request by kamilkociszewski**
Implementation of A1 Mediator for RIC TaaP as part of RIC TaaP Studio.

A1 Mediator is deployed together with GUI using Docker Compose method.
To check available APIs, type 0.0.0.0:9000/docs when RIC Taap Studio is deployed.

It allows to communicate Non and Near Real Time RICs through standardized A1 API.
Compatible rApps and xApps are delivered separatly.

### CODE REVIEW

**Comment by MinaYonan123** [comment]
Thanks Kamil
Please make this pull in a new branch for testing purposes.

**Comment by kamilkociszewski** [comment]
> Thanks Kamil Please make this pull in a new branch for testing purposes.

Mina, can you prepare new branch called e.g. "A1_dev" that i can pull into? 
I do not have access to create branches in this repo.

**Comment by MinaYonan123** [comment]
Done

**Comment by kamilkociszewski** [comment]
> Done

Done

**Pull request merged**
